on:
  push:
    branches: '*'

name: Precompile Binaries

jobs:
  Precompile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Set up Java 21 on Ubuntu 22.04 only
      - name: Set up Java 21
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Cargo.toml optimizations
        run: |
          mkdir -p .cargo
          echo "[profile.release]" >> .cargo/config.toml
          echo "opt-level = 'z'" >> .cargo/config.toml
          echo "lto = true" >> .cargo/config.toml
          echo "codegen-units = 1" >> .cargo/config.toml
          echo "panic = 'abort'" >> .cargo/config.toml

      - uses: dart-lang/setup-dart@v1

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Android SDK
        if: matrix.os == 'ubuntu-latest'
        uses: android-actions/setup-android@v2

      - name: Install Specific NDK
        if: matrix.os == 'ubuntu-latest'
        run: sdkmanager --install "ndk;26.3.11579264"

      # Precompile for Android (Linux)
      - name: Precompile (with Android)
        if: matrix.os == 'ubuntu-latest'
        env:
          CARGOKIT_ROOT_PROJECT_DIR: "cargokit/build_tool/"
          CARGOKIT_TARGET_PLATFORMS: "android-arm64"
          CARGOKIT_CONFIGURATION: "release"
          CARGOKIT_TARGET_TEMP_DIR: "/root/lib/linux"
          CARGOKIT_MANIFEST_DIR: "/app/rust"
          CARGOKIT_OUTPUT_DIR: "/root/release/linux"
          CARGOKIT_MIN_SDK_VERSION: "21"
          CARGOKIT_NDK_VERSION: "26.3.11579264"
          CARGOKIT_SDK_DIR: "/usr/local/lib/android/sdk"
          CARGOKIT_JAVA_HOME: "/usr/local/lib/jvm/java-21-openjdk-amd64"
        run: dart run build_tool build-gradle

      # Upload artifacts from CARGOKIT_TARGET_TEMP_DIR
      - name: Upload precompiled binaries
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: precompiled-binaries
          path: /root/lib/linux
